# Generated by Django 4.2.5 on 2023-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_alter_newsarticle_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(),
        ),
    ]
